version: '3'

services:
  zookeeper:
    image: zookeeper:3.7 # Updated to the official Zookeeper image with better support
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_NAME_INSIDE_PORT: 9093
      KAFKA_LISTENER_NAME_OUTSIDE_PORT: 9094
      KAFKA_LISTENER_NAME_INSIDE_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_OUTSIDE_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_NAME_OUTSIDE: OUTSIDE
      KAFKA_LISTENER_NAME_INSIDE_HOSTNAME: kafka
      KAFKA_LISTENER_NAME_OUTSIDE_HOSTNAME: localhost
      KAFKA_ADVERTISED_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_ADVERTISED_LISTENER_NAME_OUTSIDE: OUTSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE # Added this line to resolve the issue
    ports:
      - "9093:9093"
      - "9094:9094"
    depends_on:
      - zookeeper
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
